CONTAINER Mfunraymaterial
{
	NAME Mfunraymaterial;

	GROUP
	{
		MATPREVIEW FUNRAYMATERIAL_MAT_PREVIEW { OPEN; MIN_WIDTH 100; MIN_HEIGHT 100; NO_SIZE_POPUP; }
	}

	INCLUDE Mbase;

	GROUP Obaselist
	{
		BOOL MATERIAL_PAGE_PROPERTIES { HIDDEN; PAGE; PARENTMSG ID_MATERIALPROPERTIES; }
	}
	
	GROUP ID_MATERIALPROPERTIES
	{
		DEFAULT 1;
		LONG FUNRAYMATERIAL_TYPE
		{
			CYCLE
			{
				FUNRAYMATERIAL_TYPE_LAMBERT;
				FUNRAYMATERIAL_TYPE_METAL;
				FUNRAYMATERIAL_TYPE_DIELECTRIC;
				FUNRAYMATERIAL_TYPE_ISOTROPIC;
				FUNRAYMATERIAL_TYPE_DIFFUSE_LIGHT;
			}
		}
	
		SEPARATOR { }
		
		COLOR FUNRAYMATERIAL_COLOR {}
		FILENAME FUNRAYMATERIAL_COLOR_TEXTURE { }
		
		SEPARATOR { }
		
		REAL  FUNRAYMATERIAL_FUZZ { MIN 0.0; MAX 1.0; MINSLIDER 0.0; MAXSLIDER 1.0; STEP 0.001; CUSTOMGUI REALSLIDER;}
		REAL  FUNRAYMATERIAL_IOR { MIN 0.0; MINSLIDER 0.0; MAXSLIDER 4.0; STEP 0.1; CUSTOMGUI REALSLIDER;}
	}

	//INCLUDE Millum;
	INCLUDE Massign;
}
