CONTAINER Tfunraycamera
{
	NAME Tfunraycamera;
	INCLUDE Tbase;
	GROUP ID_TAGPROPERTIES
	{
		REAL FUNRAY_CAMERA_APERATURE { FIT_H ; SCALE_H ; MIN 0.0; MAXSLIDER 1.0; STEP 0.001; CUSTOMGUI REALSLIDER; ANIM OFF;} 
	}
}