#ifndef VPFUNRAY_H__
#define VPFUNRAY_H__

enum
{
	VP_FUNRAY_SAMPLES				=	1000,
	VP_FUNRAY_MAXDEPTH				=	1001,
	VP_FUNRAY_RENDERMODE_VIEWPORT	=	1002,
		VP_FUNRAY_RENDERMODE_SINGLETHREAD  = 0,
		VP_FUNRAY_RENDERMODE_MULTITHREAD   = 1,
		VP_FUNRAY_RENDERMODE_SINGLETHREAD_PROGRESSIVE = 2,
		VP_FUNRAY_RENDERMODE_MULTITHREAD_PROGRESSIVE = 3,
};

#endif // VPFUNRAY_H__
