CONTAINER VPfunray
{
	NAME VPfunray;
	INCLUDE VPbase;

	GROUP ID_VIDEOPOSTPROPERTIES
	{
		LONG VP_FUNRAY_SAMPLES { MIN 1; MAX 1000; ANIM OFF;}
		LONG VP_FUNRAY_MAXDEPTH { MIN 1; MAX 50; ANIM OFF;}
		LONG VP_FUNRAY_RENDERMODE_VIEWPORT
		{
			ANIM OFF;
			CYCLE 
			{
				VP_FUNRAY_RENDERMODE_SINGLETHREAD;
				VP_FUNRAY_RENDERMODE_MULTITHREAD;
				VP_FUNRAY_RENDERMODE_SINGLETHREAD_PROGRESSIVE;
				VP_FUNRAY_RENDERMODE_MULTITHREAD_PROGRESSIVE;	
			}
		}
	}
}
